In [5]:
import pickle
import numpy as np
import json

In [9]:
c = {'q':[], 'qdot':[], 'qddot':[]}
c['q'].append(np.array([1,2,3,4]))
c['qdot'].append(np.array([11,12,13,14]))
c['qddot'].append(np.array([111,122,133,144]))

In [6]:
with open("States_Data", "rb") as fp:
    states = pickle.load(fp)

In [7]:
states['q']

[array([ 0.   ,  0.4  ,  0.   , -2.5  ,  0.   ,  2.7  ,  0.707]),
 array([ 0.   ,  0.4  ,  0.   , -2.5  ,  0.   ,  2.7  ,  0.707]),
 array([ 0.   ,  0.4  ,  0.   , -2.5  ,  0.   ,  2.7  ,  0.707]),
 array([-2.27889636e-04,  3.99796340e-01,  1.91127445e-04, -2.49927960e+00,
        -7.83424255e-04,  2.69988880e+00,  7.06471198e-01]),
 array([-8.81296927e-04,  3.99212404e-01,  7.39129838e-04, -2.49721406e+00,
        -3.02966559e-03,  2.69956997e+00,  7.04955014e-01]),
 array([-2.12941578e-03,  3.98096986e-01,  1.78590745e-03, -2.49326852e+00,
        -7.32036788e-03,  2.69896096e+00,  7.02058843e-01]),
 array([-0.00411481,  0.39632268,  0.00345103, -2.48699232, -0.01414562,
         2.69799219,  0.69745188]),
 array([-0.00695518,  0.3937843 ,  0.0058332 , -2.47801337, -0.02391007,
         2.69660624,  0.690861  ]),
 array([-0.01074512,  0.39039731,  0.00901176, -2.46603267, -0.03693887,
         2.69475695,  0.68206672]),
 array([-0.01555779,  0.38609633,  0.01304807, -2.45081891, -0.0

In [2]:
a = [1,2,3,4]
sum(a)

10

In [1]:
int('1')

1

In [2]:
from time import perf_counter

start = perf_counter()
print()
print()
print()
print()
print()
print()
print()
print()

end = perf_counter()

print(end-start)









0.00016621800023131073


In [3]:
sum([1])

1